version: '2'
services:
  nginx:
      build:
        context: .
        dockerfile: ./docker-config/nginx/Dockerfile
      ports:
          - 80:80
          - 443:443
      volumes:
          - cpresources:/var/www/html/web/cpresources
          - ./src/web:/var/www/html/web

  php:
      build:
        context: .
        dockerfile: ./docker-config/php/Dockerfile
      expose:
          - 9000
      volumes:
          - cpresources:/var/www/html/web/cpresources
          - ./src/config:/var/www/html/config
          - ./src/templates:/var/www/html/templates
          - ./src/web:/var/www/html/web
      env_file:
          - ./src/.env
      environment:
          PMA_HOST: database
          DB_SERVER: database

  database:
      image: mariadb:10.3
      volumes:
          - db:/var/lib/mysql
          - ./db:/var/import
      ports:
          - 3306:3306
      environment:
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_DATABASE: fondationcartier
          MYSQL_USER: fondationcartier_user
          MYSQL_PASSWORD: secret

  pma:
      image: phpmyadmin/phpmyadmin
      ports:
          - 1111:80
      environment:
          PMA_HOST: database
          UPLOAD_LIMIT: 300M

volumes:
  db:
  cpresources:
  node_modules: